# This is a basic workflow that is manually triggered

name: Python application

# Controls when the action will run.
on:
  workflow_dispatch:
      # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Manual'
        # Input has to be provided for the workflow to run
        required: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # Runs a single command using the runners shell
    - name: test
      run: |
        cd ./HW1/src; python script.py -g all
    - run: echo "🍏 This job's status is ${{ job.status }}."
