# This is a basic workflow to test HW1

name: Test Report

# Controls when the action will run.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup
      run: python setup.py install
    - name: Test HW1
      id: test_hw1
      run: python HW1/src/main.py -g all
    - name: Test HW2
      id: test_hw2
      run: python HW2/src/main.py -g all -f ./HW2/etc/data/auto93.csv
    - name: Test HW3
      id: test_hw3
      run: python HW3/src/main.py -g all -f ./HW3/etc/data/auto93.csv
    - name: Test HW4
      id: test_hw4
      run: python HW4/src/main.py -g all -f ./HW4/etc/data/repgrid1.csv
    - name: Test HW5
      id: test_hw5
      run: python HW5/src/main.py -g all -f ./HW5/etc/data/auto93.csv
    - name: Test HW6
      id: test_hw6
      run: python HW6/src/main.py -g all -f ./HW6/etc/data/auto93.csv
    - run: echo "🍏 This job's status is ${{ job.status }}."
